  spring:
    profiles:
        active:
            -dev
---
server:
    port: 8001
spring:
    profiles: dev ## 开发环境
    application:
        name: config-dept-client
    datasource:
    type: com.alibaba.druid.pool.DruidDataSource      # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver       # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud_db?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai    # 数据库名称
    username: root1809
    password: root1809
    dbcp2:
      min-idle: 5             # 数据库连接池的最小维持连接数
      initial-size: 5         # 初始化连接数
      max-total: 5            # 最大连接数
      max-wait-millis: 5000   # 等待连接获取的最大超时时间
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
  type-aliases-package: com.xiaoduo.entity    # 所有Entity别名类所在包
  mapper-locations: mybatis/mapper/*.xml                  # mapper映射文件
eureka:
    client:
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/
info:
  app.name: config-dept-client8001
  company.name: www.xiaoduo.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
---
server:
    port: 8001
spring:
    profiles: test ## 开发环境
    application:
        name: config-dept-client
    datasource:
    type: com.alibaba.druid.pool.DruidDataSource      # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver       # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud_db2?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai    # 数据库名称
    username: root1809
    password: root1809
    dbcp2:
      min-idle: 5             # 数据库连接池的最小维持连接数
      initial-size: 5         # 初始化连接数
      max-total: 5            # 最大连接数
      max-wait-millis: 5000   # 等待连接获取的最大超时时间
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
  type-aliases-package: com.xiaoduo.entity    # 所有Entity别名类所在包
  mapper-locations: mybatis/mapper/*.xml                  # mapper映射文件
eureka:
    client:
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/
info:
  app.name: config-dept-client8001
  company.name: www.xiaoduo.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
## 请保存为UTF-8格式